apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "comanage.fullname" . }}
  labels:
    app: {{ template "comanage.name" . }}
    chart: {{ template "comanage.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "comanage.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "comanage.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: etc-comanage
          configMap:
            name:  {{ .Release.Name }}-configmap 
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "postgresql.fullname" . }}
                  key: postgres-password
            - name: DB_HOST
              value: {{ template "postgresql.fullname" . }}
            - name: DB_USER
              value: "comanage"
            - name: DB_NAME
              value: "comanage"
            - name: ADMIN_GIVEN_NAME
              value: "Alfred"
            - name: ADMIN_FAMILY_NAME
              value: "Wessex"
            - name: ADMIN_USERNAME
              value: "admin@bar.ac.uk"
          volumeMounts:
            - mountPath: /etc/comanage
              name: etc-comanage
            
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
